### ISSUE TITLE
Mobile welcome text getting cut off based on the font selection

### ISSUE THREAD

**Issue by Chrisbrozek** [bigcartel-themes/neat#58]
If you set the font style to Helvetica and type in a longish welcome text (for example, "in collaboration with REPRESENT"), the text on the right side of the screen is cropped on iPhones. In that example, the word "collaboration" is cropped. If you're just sizing your browser to a mobile screen size it looks totally fine, but if you actually test this on a phone, it's cropped. The following CSS override fixes it:

@media only screen and (max-width: 400px) {
  .slideshow div.featured h2 {
    font-size: 2em;
  }
}

Here's an example of that cropped welcome text on an iPhone before adding the CSS override:

![](http://s28.postimg.org/gvk4qsznh/IMG_5366.png)

**Comment by nickendle** [comment]
this is all fixed up
